# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ts/projects/cpp_projects/learning_opengl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ts/projects/cpp_projects/learning_opengl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ts/projects/cpp_projects/learning_opengl/CMakeFiles /home/ts/projects/cpp_projects/learning_opengl//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ts/projects/cpp_projects/learning_opengl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named blinkingtri

# Build rule for target.
blinkingtri: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blinkingtri
.PHONY : blinkingtri

# fast build rule for target.
blinkingtri/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinkingtri.dir/build.make CMakeFiles/blinkingtri.dir/build
.PHONY : blinkingtri/fast

#=============================================================================
# Target rules for targets named colorfultri

# Build rule for target.
colorfultri: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 colorfultri
.PHONY : colorfultri

# fast build rule for target.
colorfultri/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorfultri.dir/build.make CMakeFiles/colorfultri.dir/build
.PHONY : colorfultri/fast

#=============================================================================
# Target rules for targets named drawrec

# Build rule for target.
drawrec: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 drawrec
.PHONY : drawrec

# fast build rule for target.
drawrec/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drawrec.dir/build.make CMakeFiles/drawrec.dir/build
.PHONY : drawrec/fast

#=============================================================================
# Target rules for targets named going3d

# Build rule for target.
going3d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 going3d
.PHONY : going3d

# fast build rule for target.
going3d/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/going3d.dir/build.make CMakeFiles/going3d.dir/build
.PHONY : going3d/fast

#=============================================================================
# Target rules for targets named texturedRec

# Build rule for target.
texturedRec: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 texturedRec
.PHONY : texturedRec

# fast build rule for target.
texturedRec/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texturedRec.dir/build.make CMakeFiles/texturedRec.dir/build
.PHONY : texturedRec/fast

#=============================================================================
# Target rules for targets named transformRec

# Build rule for target.
transformRec: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 transformRec
.PHONY : transformRec

# fast build rule for target.
transformRec/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transformRec.dir/build.make CMakeFiles/transformRec.dir/build
.PHONY : transformRec/fast

src/sources/blinkingtri.o: src/sources/blinkingtri.cpp.o
.PHONY : src/sources/blinkingtri.o

# target to build an object file
src/sources/blinkingtri.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinkingtri.dir/build.make CMakeFiles/blinkingtri.dir/src/sources/blinkingtri.cpp.o
.PHONY : src/sources/blinkingtri.cpp.o

src/sources/blinkingtri.i: src/sources/blinkingtri.cpp.i
.PHONY : src/sources/blinkingtri.i

# target to preprocess a source file
src/sources/blinkingtri.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinkingtri.dir/build.make CMakeFiles/blinkingtri.dir/src/sources/blinkingtri.cpp.i
.PHONY : src/sources/blinkingtri.cpp.i

src/sources/blinkingtri.s: src/sources/blinkingtri.cpp.s
.PHONY : src/sources/blinkingtri.s

# target to generate assembly for a file
src/sources/blinkingtri.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinkingtri.dir/build.make CMakeFiles/blinkingtri.dir/src/sources/blinkingtri.cpp.s
.PHONY : src/sources/blinkingtri.cpp.s

src/sources/colorfultri.o: src/sources/colorfultri.cpp.o
.PHONY : src/sources/colorfultri.o

# target to build an object file
src/sources/colorfultri.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorfultri.dir/build.make CMakeFiles/colorfultri.dir/src/sources/colorfultri.cpp.o
.PHONY : src/sources/colorfultri.cpp.o

src/sources/colorfultri.i: src/sources/colorfultri.cpp.i
.PHONY : src/sources/colorfultri.i

# target to preprocess a source file
src/sources/colorfultri.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorfultri.dir/build.make CMakeFiles/colorfultri.dir/src/sources/colorfultri.cpp.i
.PHONY : src/sources/colorfultri.cpp.i

src/sources/colorfultri.s: src/sources/colorfultri.cpp.s
.PHONY : src/sources/colorfultri.s

# target to generate assembly for a file
src/sources/colorfultri.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorfultri.dir/build.make CMakeFiles/colorfultri.dir/src/sources/colorfultri.cpp.s
.PHONY : src/sources/colorfultri.cpp.s

src/sources/drawrec.o: src/sources/drawrec.cpp.o
.PHONY : src/sources/drawrec.o

# target to build an object file
src/sources/drawrec.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drawrec.dir/build.make CMakeFiles/drawrec.dir/src/sources/drawrec.cpp.o
.PHONY : src/sources/drawrec.cpp.o

src/sources/drawrec.i: src/sources/drawrec.cpp.i
.PHONY : src/sources/drawrec.i

# target to preprocess a source file
src/sources/drawrec.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drawrec.dir/build.make CMakeFiles/drawrec.dir/src/sources/drawrec.cpp.i
.PHONY : src/sources/drawrec.cpp.i

src/sources/drawrec.s: src/sources/drawrec.cpp.s
.PHONY : src/sources/drawrec.s

# target to generate assembly for a file
src/sources/drawrec.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drawrec.dir/build.make CMakeFiles/drawrec.dir/src/sources/drawrec.cpp.s
.PHONY : src/sources/drawrec.cpp.s

src/sources/going3d.o: src/sources/going3d.cpp.o
.PHONY : src/sources/going3d.o

# target to build an object file
src/sources/going3d.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/going3d.dir/build.make CMakeFiles/going3d.dir/src/sources/going3d.cpp.o
.PHONY : src/sources/going3d.cpp.o

src/sources/going3d.i: src/sources/going3d.cpp.i
.PHONY : src/sources/going3d.i

# target to preprocess a source file
src/sources/going3d.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/going3d.dir/build.make CMakeFiles/going3d.dir/src/sources/going3d.cpp.i
.PHONY : src/sources/going3d.cpp.i

src/sources/going3d.s: src/sources/going3d.cpp.s
.PHONY : src/sources/going3d.s

# target to generate assembly for a file
src/sources/going3d.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/going3d.dir/build.make CMakeFiles/going3d.dir/src/sources/going3d.cpp.s
.PHONY : src/sources/going3d.cpp.s

src/sources/texturedRec.o: src/sources/texturedRec.cpp.o
.PHONY : src/sources/texturedRec.o

# target to build an object file
src/sources/texturedRec.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texturedRec.dir/build.make CMakeFiles/texturedRec.dir/src/sources/texturedRec.cpp.o
.PHONY : src/sources/texturedRec.cpp.o

src/sources/texturedRec.i: src/sources/texturedRec.cpp.i
.PHONY : src/sources/texturedRec.i

# target to preprocess a source file
src/sources/texturedRec.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texturedRec.dir/build.make CMakeFiles/texturedRec.dir/src/sources/texturedRec.cpp.i
.PHONY : src/sources/texturedRec.cpp.i

src/sources/texturedRec.s: src/sources/texturedRec.cpp.s
.PHONY : src/sources/texturedRec.s

# target to generate assembly for a file
src/sources/texturedRec.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texturedRec.dir/build.make CMakeFiles/texturedRec.dir/src/sources/texturedRec.cpp.s
.PHONY : src/sources/texturedRec.cpp.s

src/sources/transformRec.o: src/sources/transformRec.cpp.o
.PHONY : src/sources/transformRec.o

# target to build an object file
src/sources/transformRec.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transformRec.dir/build.make CMakeFiles/transformRec.dir/src/sources/transformRec.cpp.o
.PHONY : src/sources/transformRec.cpp.o

src/sources/transformRec.i: src/sources/transformRec.cpp.i
.PHONY : src/sources/transformRec.i

# target to preprocess a source file
src/sources/transformRec.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transformRec.dir/build.make CMakeFiles/transformRec.dir/src/sources/transformRec.cpp.i
.PHONY : src/sources/transformRec.cpp.i

src/sources/transformRec.s: src/sources/transformRec.cpp.s
.PHONY : src/sources/transformRec.s

# target to generate assembly for a file
src/sources/transformRec.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transformRec.dir/build.make CMakeFiles/transformRec.dir/src/sources/transformRec.cpp.s
.PHONY : src/sources/transformRec.cpp.s

src/tools/glad/glad.o: src/tools/glad/glad.c.o
.PHONY : src/tools/glad/glad.o

# target to build an object file
src/tools/glad/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinkingtri.dir/build.make CMakeFiles/blinkingtri.dir/src/tools/glad/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorfultri.dir/build.make CMakeFiles/colorfultri.dir/src/tools/glad/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drawrec.dir/build.make CMakeFiles/drawrec.dir/src/tools/glad/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/going3d.dir/build.make CMakeFiles/going3d.dir/src/tools/glad/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texturedRec.dir/build.make CMakeFiles/texturedRec.dir/src/tools/glad/glad.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transformRec.dir/build.make CMakeFiles/transformRec.dir/src/tools/glad/glad.c.o
.PHONY : src/tools/glad/glad.c.o

src/tools/glad/glad.i: src/tools/glad/glad.c.i
.PHONY : src/tools/glad/glad.i

# target to preprocess a source file
src/tools/glad/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinkingtri.dir/build.make CMakeFiles/blinkingtri.dir/src/tools/glad/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorfultri.dir/build.make CMakeFiles/colorfultri.dir/src/tools/glad/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drawrec.dir/build.make CMakeFiles/drawrec.dir/src/tools/glad/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/going3d.dir/build.make CMakeFiles/going3d.dir/src/tools/glad/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texturedRec.dir/build.make CMakeFiles/texturedRec.dir/src/tools/glad/glad.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transformRec.dir/build.make CMakeFiles/transformRec.dir/src/tools/glad/glad.c.i
.PHONY : src/tools/glad/glad.c.i

src/tools/glad/glad.s: src/tools/glad/glad.c.s
.PHONY : src/tools/glad/glad.s

# target to generate assembly for a file
src/tools/glad/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinkingtri.dir/build.make CMakeFiles/blinkingtri.dir/src/tools/glad/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorfultri.dir/build.make CMakeFiles/colorfultri.dir/src/tools/glad/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drawrec.dir/build.make CMakeFiles/drawrec.dir/src/tools/glad/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/going3d.dir/build.make CMakeFiles/going3d.dir/src/tools/glad/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texturedRec.dir/build.make CMakeFiles/texturedRec.dir/src/tools/glad/glad.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transformRec.dir/build.make CMakeFiles/transformRec.dir/src/tools/glad/glad.c.s
.PHONY : src/tools/glad/glad.c.s

src/tools/objectdrawer.o: src/tools/objectdrawer.cpp.o
.PHONY : src/tools/objectdrawer.o

# target to build an object file
src/tools/objectdrawer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinkingtri.dir/build.make CMakeFiles/blinkingtri.dir/src/tools/objectdrawer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorfultri.dir/build.make CMakeFiles/colorfultri.dir/src/tools/objectdrawer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drawrec.dir/build.make CMakeFiles/drawrec.dir/src/tools/objectdrawer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/going3d.dir/build.make CMakeFiles/going3d.dir/src/tools/objectdrawer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texturedRec.dir/build.make CMakeFiles/texturedRec.dir/src/tools/objectdrawer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transformRec.dir/build.make CMakeFiles/transformRec.dir/src/tools/objectdrawer.cpp.o
.PHONY : src/tools/objectdrawer.cpp.o

src/tools/objectdrawer.i: src/tools/objectdrawer.cpp.i
.PHONY : src/tools/objectdrawer.i

# target to preprocess a source file
src/tools/objectdrawer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinkingtri.dir/build.make CMakeFiles/blinkingtri.dir/src/tools/objectdrawer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorfultri.dir/build.make CMakeFiles/colorfultri.dir/src/tools/objectdrawer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drawrec.dir/build.make CMakeFiles/drawrec.dir/src/tools/objectdrawer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/going3d.dir/build.make CMakeFiles/going3d.dir/src/tools/objectdrawer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texturedRec.dir/build.make CMakeFiles/texturedRec.dir/src/tools/objectdrawer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transformRec.dir/build.make CMakeFiles/transformRec.dir/src/tools/objectdrawer.cpp.i
.PHONY : src/tools/objectdrawer.cpp.i

src/tools/objectdrawer.s: src/tools/objectdrawer.cpp.s
.PHONY : src/tools/objectdrawer.s

# target to generate assembly for a file
src/tools/objectdrawer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinkingtri.dir/build.make CMakeFiles/blinkingtri.dir/src/tools/objectdrawer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorfultri.dir/build.make CMakeFiles/colorfultri.dir/src/tools/objectdrawer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drawrec.dir/build.make CMakeFiles/drawrec.dir/src/tools/objectdrawer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/going3d.dir/build.make CMakeFiles/going3d.dir/src/tools/objectdrawer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texturedRec.dir/build.make CMakeFiles/texturedRec.dir/src/tools/objectdrawer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transformRec.dir/build.make CMakeFiles/transformRec.dir/src/tools/objectdrawer.cpp.s
.PHONY : src/tools/objectdrawer.cpp.s

src/tools/shader.o: src/tools/shader.cpp.o
.PHONY : src/tools/shader.o

# target to build an object file
src/tools/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinkingtri.dir/build.make CMakeFiles/blinkingtri.dir/src/tools/shader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorfultri.dir/build.make CMakeFiles/colorfultri.dir/src/tools/shader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drawrec.dir/build.make CMakeFiles/drawrec.dir/src/tools/shader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/going3d.dir/build.make CMakeFiles/going3d.dir/src/tools/shader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texturedRec.dir/build.make CMakeFiles/texturedRec.dir/src/tools/shader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transformRec.dir/build.make CMakeFiles/transformRec.dir/src/tools/shader.cpp.o
.PHONY : src/tools/shader.cpp.o

src/tools/shader.i: src/tools/shader.cpp.i
.PHONY : src/tools/shader.i

# target to preprocess a source file
src/tools/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinkingtri.dir/build.make CMakeFiles/blinkingtri.dir/src/tools/shader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorfultri.dir/build.make CMakeFiles/colorfultri.dir/src/tools/shader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drawrec.dir/build.make CMakeFiles/drawrec.dir/src/tools/shader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/going3d.dir/build.make CMakeFiles/going3d.dir/src/tools/shader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texturedRec.dir/build.make CMakeFiles/texturedRec.dir/src/tools/shader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transformRec.dir/build.make CMakeFiles/transformRec.dir/src/tools/shader.cpp.i
.PHONY : src/tools/shader.cpp.i

src/tools/shader.s: src/tools/shader.cpp.s
.PHONY : src/tools/shader.s

# target to generate assembly for a file
src/tools/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinkingtri.dir/build.make CMakeFiles/blinkingtri.dir/src/tools/shader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorfultri.dir/build.make CMakeFiles/colorfultri.dir/src/tools/shader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drawrec.dir/build.make CMakeFiles/drawrec.dir/src/tools/shader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/going3d.dir/build.make CMakeFiles/going3d.dir/src/tools/shader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texturedRec.dir/build.make CMakeFiles/texturedRec.dir/src/tools/shader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transformRec.dir/build.make CMakeFiles/transformRec.dir/src/tools/shader.cpp.s
.PHONY : src/tools/shader.cpp.s

src/tools/stb_image.o: src/tools/stb_image.cpp.o
.PHONY : src/tools/stb_image.o

# target to build an object file
src/tools/stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinkingtri.dir/build.make CMakeFiles/blinkingtri.dir/src/tools/stb_image.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorfultri.dir/build.make CMakeFiles/colorfultri.dir/src/tools/stb_image.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drawrec.dir/build.make CMakeFiles/drawrec.dir/src/tools/stb_image.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/going3d.dir/build.make CMakeFiles/going3d.dir/src/tools/stb_image.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texturedRec.dir/build.make CMakeFiles/texturedRec.dir/src/tools/stb_image.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transformRec.dir/build.make CMakeFiles/transformRec.dir/src/tools/stb_image.cpp.o
.PHONY : src/tools/stb_image.cpp.o

src/tools/stb_image.i: src/tools/stb_image.cpp.i
.PHONY : src/tools/stb_image.i

# target to preprocess a source file
src/tools/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinkingtri.dir/build.make CMakeFiles/blinkingtri.dir/src/tools/stb_image.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorfultri.dir/build.make CMakeFiles/colorfultri.dir/src/tools/stb_image.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drawrec.dir/build.make CMakeFiles/drawrec.dir/src/tools/stb_image.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/going3d.dir/build.make CMakeFiles/going3d.dir/src/tools/stb_image.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texturedRec.dir/build.make CMakeFiles/texturedRec.dir/src/tools/stb_image.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transformRec.dir/build.make CMakeFiles/transformRec.dir/src/tools/stb_image.cpp.i
.PHONY : src/tools/stb_image.cpp.i

src/tools/stb_image.s: src/tools/stb_image.cpp.s
.PHONY : src/tools/stb_image.s

# target to generate assembly for a file
src/tools/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blinkingtri.dir/build.make CMakeFiles/blinkingtri.dir/src/tools/stb_image.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/colorfultri.dir/build.make CMakeFiles/colorfultri.dir/src/tools/stb_image.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/drawrec.dir/build.make CMakeFiles/drawrec.dir/src/tools/stb_image.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/going3d.dir/build.make CMakeFiles/going3d.dir/src/tools/stb_image.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/texturedRec.dir/build.make CMakeFiles/texturedRec.dir/src/tools/stb_image.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transformRec.dir/build.make CMakeFiles/transformRec.dir/src/tools/stb_image.cpp.s
.PHONY : src/tools/stb_image.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... blinkingtri"
	@echo "... colorfultri"
	@echo "... drawrec"
	@echo "... going3d"
	@echo "... texturedRec"
	@echo "... transformRec"
	@echo "... src/sources/blinkingtri.o"
	@echo "... src/sources/blinkingtri.i"
	@echo "... src/sources/blinkingtri.s"
	@echo "... src/sources/colorfultri.o"
	@echo "... src/sources/colorfultri.i"
	@echo "... src/sources/colorfultri.s"
	@echo "... src/sources/drawrec.o"
	@echo "... src/sources/drawrec.i"
	@echo "... src/sources/drawrec.s"
	@echo "... src/sources/going3d.o"
	@echo "... src/sources/going3d.i"
	@echo "... src/sources/going3d.s"
	@echo "... src/sources/texturedRec.o"
	@echo "... src/sources/texturedRec.i"
	@echo "... src/sources/texturedRec.s"
	@echo "... src/sources/transformRec.o"
	@echo "... src/sources/transformRec.i"
	@echo "... src/sources/transformRec.s"
	@echo "... src/tools/glad/glad.o"
	@echo "... src/tools/glad/glad.i"
	@echo "... src/tools/glad/glad.s"
	@echo "... src/tools/objectdrawer.o"
	@echo "... src/tools/objectdrawer.i"
	@echo "... src/tools/objectdrawer.s"
	@echo "... src/tools/shader.o"
	@echo "... src/tools/shader.i"
	@echo "... src/tools/shader.s"
	@echo "... src/tools/stb_image.o"
	@echo "... src/tools/stb_image.i"
	@echo "... src/tools/stb_image.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

